# Generated by Django 3.2.2 on 2021-10-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TprLab1Dohod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDohod', models.CharField(max_length=30)),
                ('good_good', models.FloatField(null=True)),
                ('good_bad', models.FloatField()),
                ('bad_good', models.FloatField(null=True)),
                ('bad_bad', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TprLab1Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numStrategy', models.CharField(max_length=30, null=True)),
                ('good_good', models.FloatField(null=True)),
                ('good_bad', models.FloatField()),
                ('bad_good', models.FloatField(null=True)),
                ('bad_bad', models.FloatField(null=True)),
            ],
        ),
    ]
