# Generated by Django 3.2.2 on 2021-10-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tprlab1dohod',
            name='good_bad',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tprlab1strategy',
            name='good_bad',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tprlab1strategy',
            name='numStrategy',
            field=models.CharField(max_length=30),
        ),
    ]
