# Generated by Django 3.2.2 on 2021-12-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TprLab1DohodsExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDohodExample', models.CharField(max_length=30, null=True)),
                ('one_one', models.FloatField(null=True)),
                ('one_two', models.FloatField(null=True)),
                ('one_three', models.FloatField(null=True)),
                ('two_one', models.FloatField(null=True)),
                ('two_two', models.FloatField(null=True)),
                ('two_three', models.FloatField(null=True)),
                ('three_one', models.FloatField(null=True)),
                ('three_two', models.FloatField(null=True)),
                ('three_three', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TprLab1StrategyExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numStrategyExample', models.CharField(max_length=30, null=True)),
                ('one_one', models.FloatField(null=True)),
                ('one_two', models.FloatField(null=True)),
                ('one_three', models.FloatField(null=True)),
                ('two_one', models.FloatField(null=True)),
                ('two_two', models.FloatField(null=True)),
                ('two_three', models.FloatField(null=True)),
                ('three_one', models.FloatField(null=True)),
                ('three_two', models.FloatField(null=True)),
                ('three_three', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TprLab6StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('stockDate', models.DateField()),
                ('stockOpen', models.FloatField()),
                ('stockHigh', models.FloatField()),
                ('stockLow', models.FloatField()),
                ('stockClose', models.FloatField()),
                ('stockVol', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tprlab1dohod',
            name='good_bad',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tprlab1dohod',
            name='numDohod',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tprlab1strategy',
            name='good_bad',
            field=models.FloatField(null=True),
        ),
    ]
