# Generated by Django 3.2.2 on 2021-10-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211028_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tprlab1strategy',
            name='numStrategy',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
