# Generated by Django 3.2.2 on 2021-10-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tprlab1strategy_numstrategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tprlab1dohod',
            name='numDohod',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
