# Generated by Django 3.2.2 on 2021-11-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tprlab1dohod_numdohod'),
    ]

    operations = [
        migrations.CreateModel(
            name='TprLab1DohodsExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDohodExample', models.CharField(max_length=30, null=True)),
                ('one_one', models.FloatField(null=True)),
                ('one_two', models.FloatField(null=True)),
                ('one_three', models.FloatField(null=True)),
                ('two_one', models.FloatField(null=True)),
                ('two_two', models.FloatField(null=True)),
                ('two_three', models.FloatField(null=True)),
                ('three_one', models.FloatField(null=True)),
                ('three_two', models.FloatField(null=True)),
                ('three_three', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TprLab1StrategyExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numStrategyExample', models.CharField(max_length=30, null=True)),
                ('one_one', models.FloatField(null=True)),
                ('one_two', models.FloatField(null=True)),
                ('one_three', models.FloatField(null=True)),
                ('two_one', models.FloatField(null=True)),
                ('two_two', models.FloatField(null=True)),
                ('two_three', models.FloatField(null=True)),
                ('three_one', models.FloatField(null=True)),
                ('three_two', models.FloatField(null=True)),
                ('three_three', models.FloatField(null=True)),
            ],
        ),
    ]
